# -*- coding: utf-8 -*-
"""Vois Major project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QHBbQKREtkk5-6XDdSLVhfCl7CPE_qnx

# **Major Data Analytics Project**
**Domain**:Agriculture

**Project Theme:** Seasonal Agriculture Performance

**Tools:** Python,Pandas,Numpy,Matplotlib,Seaborn

# **1.Problem Statement**

*   Agricultural activities are heavily influenced by seasonal variations in environmental conditions, farming practices, resource availability, and market dynamics.
*   Raw agricultural data often fails to clearly explain how performance changes across seasons or what underlying patterns exist under different environmental conditions.

*   The Core Challenge: Investigate seasonal differences in agricultural performance by identifying meaningful patterns, trends, relationships, and variations within the available agricultural dataset to drive data-backed decision-making.

# **2.Primary Objectives**

* Investigate and evaluate seasonal differences in agricultural performance by examining environmental conditions, farming practices, and resource availability.
* Identify meaningful patterns, trends, relationships, and variations within the available agricultural dataset.
* Assess how input factors, cost structures, and irrigation methodologies impact farm-level productivity and net profitability.

# **3.Dataset**
The dataset contains 4,000 agricultural records spanning multiple states, districts, seasons, and irrigation topologies to evaluate farm-level productivity, cost structures, and financial returns. It encompasses key environmental, input, and economic variables—including rainfall, temperature, soil pH, fertilizer application, crop yields, total costs, revenues, and net profitability.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv('/content/seasonal_agriculture_performance_dataset (1).csv')

"""**Review top and bottom rows**"""

display(df.head())
display(df.tail())

"""**Check dimensions, column names, and data types**"""

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.to_list())
df.info()

"""**Comprehensive statistical summary**"""

df.describe(include='all').T

"""**Check for duplicate rows and missing values before cleaning**"""

duplicate_count = df.duplicated().sum()
print(f"Duplicate Rows: {duplicate_count}")

missing = pd.DataFrame({
    'Missing Count': df.isna().sum(),
    'Missing %': (df.isna().mean() * 100).round(2)
})
display(missing[missing['Missing Count'] > 0].sort_values('Missing Count', ascending=False))

"""# Data Cleaning & Imputation Strategy
**Impute numerical missing values with median and Verify missing values after cleaning**


"""

for col in ['Rainfall_mm', 'Soil_Moisture_pct', 'Yield_Tonnes_Ha']:
    if col in df.columns:
        df[col] = df[col].fillna(df[col].median())

print("Missing values remaining:", df.isna().sum().sum())

"""**Key metrics grouped by Crop and State**"""

crop_summary = df.groupby('Crop').agg({
    'Production_Tonnes': 'sum',
    'Yield_Tonnes_Ha': 'mean',
    'Profit_INR': 'mean',
    'Water_Efficiency_t_per_1000m3': 'mean'
}).reset_index()

display(crop_summary)

# Average metrics
avg_profit = df['Profit_INR'].mean()
median_profit = df['Profit_INR'].median()
print(f"Average Profit: ₹{avg_profit:,.2f}")
print(f"Median Profit: ₹{median_profit:,.2f}")

"""**Chart 1: Total Production by Crop Type**"""

crop_prod = df.groupby('Crop')['Production_Tonnes'].sum()
plt.figure(figsize=(10, 5))
crop_prod.plot(kind='bar', color='forestgreen')
plt.title('Total Production by Crop Type')
plt.xlabel('Crop')
plt.ylabel('Production (Tonnes)')
plt.xticks(rotation=25)
plt.tight_layout()
plt.show()

"""**Chart 2: Profit Distribution by Irrigation Method**"""

plt.figure(figsize=(10, 6))
sns.boxplot(x='Irrigation_Method', y='Profit_INR', data=df, palette='Set2')
plt.title('Profit Distribution by Irrigation Method')
plt.xlabel('Irrigation Method')
plt.ylabel('Profit (INR)')
plt.tight_layout()
plt.show()

"""**Chart 3: Scatter Plot between Fertilizer Usage and Yield**"""

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Fertilizer_kg_ha', y='Yield_Tonnes_Ha', data=df, hue='Season', alpha=0.7)
plt.title('Fertilizer Usage vs. Crop Yield')
plt.xlabel('Fertilizer (kg/ha)')
plt.ylabel('Yield (Tonnes/Ha)')
plt.tight_layout()
plt.show()

"""**Multi-Panel Dashboard (2x2 Grid)**"""

fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle('Agricultural Performance Dashboard', fontsize=20, fontweight='bold')

# Subplot 1
crop_prod.plot(kind='bar', ax=axes[0, 0], color='forestgreen')
axes[0, 0].set_title('1. Total Production by Crop')
axes[0, 0].set_xlabel('Crop')
axes[0, 0].set_ylabel('Production (Tonnes)')
axes[0, 0].tick_params(axis='x', rotation=25)

# Subplot 2
sns.barplot(x='State', y='Revenue_INR', data=df, ax=axes[0, 1], estimator=np.mean, palette='viridis')
axes[0, 1].set_title('2. Average Revenue by State')
axes[0, 1].set_xlabel('State')
axes[0, 1].set_ylabel('Revenue (INR)')
axes[0, 1].tick_params(axis='x', rotation=45)

# Subplot 3
sns.boxplot(x='Irrigation_Method', y='Profit_INR', data=df, ax=axes[1, 0], palette='Set2')
axes[1, 0].set_title('3. Profit Distribution by Irrigation Method')
axes[1, 0].set_xlabel('Irrigation Method')
axes[1, 0].set_ylabel('Profit (INR)')

# Subplot 4
sns.scatterplot(x='Rainfall_mm', y='Yield_Tonnes_Ha', data=df, hue='Season', ax=axes[1, 1], alpha=0.6)
axes[1, 1].set_title('4. Rainfall vs. Crop Yield')
axes[1, 1].set_xlabel('Rainfall (mm)')
axes[1, 1].set_ylabel('Yield (Tonnes/Ha)')

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

"""**Seasonal Comparison Analysis: Grouping key performance metrics by Season**"""

seasonal_summary = df.groupby('Season').agg({
    'Yield_Tonnes_Ha': 'mean',
    'Profit_INR': 'mean',
    'Total_Cost_INR': 'mean',
    'Water_Efficiency_t_per_1000m3': 'mean'
}).reset_index()

display(seasonal_summary)

# Visualizing Seasonal Comparison (Profit & Yield across Seasons)
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Plot 1: Average Profit by Season

sns.barplot(data=df, x='Season', y='Profit_INR',hue='Season', estimator='mean', ax=axes[0], palette='Set2',legend=False)
axes[0].set_title('Average Net Profit by Season', fontsize=12, fontweight='bold')
axes[0].set_xlabel('Season')
axes[0].set_ylabel('Mean Profit (INR)')

# Plot 2: Average Yield by Season

sns.barplot(data=df, x='Season', y='Yield_Tonnes_Ha',hue='Season', estimator='mean', ax=axes[1], palette='crest',legend=False)
axes[1].set_title('Average Crop Yield by Season', fontsize=12, fontweight='bold')
axes[1].set_xlabel('Season')
axes[1].set_ylabel('Mean Yield (Tonnes/Ha)')

plt.tight_layout()
plt.show()

"""**Cost-to-Profit Quadrant Analysis & Return on Investment (ROI) Distribution**"""

# Calculate ROI percentage if it doesn't already exist in the dataframe
df['ROI_pct'] = (df['Profit_INR'] / df['Total_Cost_INR']) * 100

# Set up the figure dimensions
plt.figure(figsize=(10, 6))

# Create a scatter plot mapping Total Cost vs. Profit, colored and sized by ROI
scatter = sns.scatterplot(
    data=df,
    x='Total_Cost_INR',
    y='Profit_INR',
    hue='ROI_pct',
    palette='coolwarm',
    alpha=0.8,
    s=60
)

# Add quadrant reference lines at zero profit and median cost
median_cost = df['Total_Cost_INR'].median()
plt.axhline(0, color='black', linestyle='--', linewidth=1, label='Break-even Line (Zero Profit)')
plt.axvline(median_cost, color='gray', linestyle=':', linewidth=1, label='Median Cost Threshold')

# Add titles and labels
plt.title('Farm Risk & ROI Quadrant Analysis: Total Cost vs. Profit', fontsize=14, fontweight='bold', pad=15)
plt.xlabel('Total Cost (INR)', fontsize=12)
plt.ylabel('Profit (INR)', fontsize=12)

# Customize legend and layout
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', title='ROI (%)')
plt.tight_layout()

# Save and display the plot
plt.savefig('farm_roi_matrix.png', dpi=300)
plt.show()

"""**Outlier Investigation using Interquartile Range (IQR)**"""

numeric_cols = ['Yield_Tonnes_Ha', 'Total_Cost_INR', 'Profit_INR', 'Rainfall_mm']

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    print(f"{col}: Found {len(outliers)} potential outliers (Out of {len(df)} rows)")

# Visualize outliers with boxplots
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
sns.boxplot(y=df['Yield_Tonnes_Ha'], color='skyblue')
plt.title('Yield Outlier Distribution')

plt.subplot(1, 2, 2)
sns.boxplot(y=df['Profit_INR'], color='salmon')
plt.title('Profit Outlier Distribution')
plt.tight_layout()
plt.show()

# Define key numerical columns to analyze for outliers
num_cols = ['Yield_Tonnes_Ha', 'Total_Cost_INR', 'Profit_INR', 'Rainfall_mm', 'Fertilizer_kg_ha', 'Water_Used_m3']
outlier_summary = []

for col in num_cols:
    series = df[col].dropna()
    Q1 = series.quantile(0.25)
    Q3 = series.quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Identify outliers beyond the 1.5 * IQR bounds
    outliers = series[(series < lower_bound) | (series > upper_bound)]

    outlier_summary.append({
        'Metric / Column': col,
        'Q1 (25%)': round(Q1, 2),
        'Q3 (75%)': round(Q3, 2),
        'IQR': round(IQR, 2),
        'Lower Bound': round(lower_bound, 2),
        'Upper Bound': round(upper_bound, 2),
        'Outlier Count': len(outliers),
        'Outlier %': round((len(outliers) / len(series)) * 100, 2)
    })

# Convert to DataFrame for neat display
outlier_df = pd.DataFrame(outlier_summary)
display(outlier_df)

plt.figure(figsize=(7,7))
df['Season'].value_counts().plot.pie(autopct='%1.1f',startangle=90,cmap='viridis')
plt.title('Distribution of Seasons')
plt.ylabel('')
plt.tight_layout()
plt.show()

"""**Correlation Analysis**"""

plt.figure(figsize=(12, 10))
corr_matrix = df[['Rainfall_mm', 'Avg_Temperature_C', 'Humidity_pct', 'Soil_pH',
                  'Fertilizer_kg_ha', 'Yield_Tonnes_Ha', 'Total_Cost_INR', 'Revenue_INR', 'Profit_INR']].corr()

sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title('Correlation Matrix of Agricultural & Financial Metrics', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

"""## Comprehensive Project Conclusion & Agricultural Insights

The comprehensive exploratory data analysis, statistical evaluation, and multi-variable modeling of the agricultural performance dataset successfully deliver granular, data-driven insights into farm-level productivity, cost structures, and profitability drivers. By evaluating 4,000 agricultural records across multiple states, districts, seasons, and irrigation topologies, the project establishes a robust framework for understanding modern agricultural performance dynamics.

### Summary of Key Findings

* **Production Volume Polarization:** Production volume is heavily dominated by commercial and high-density biomass crops like Sugarcane, which accounts for the vast majority of total national production tonnage due to exceptionally high yields per hectare compared to staple cereals and pulses.


* **Financial Profitability Disparity:** A striking divergence exists between production volume and net profitability. While staple crops like Wheat, Rice, and Maize often operate near break-even or record negative net margins due to high operational expenditures, specialized commercial crops like Sugarcane and Chilli achieve high median profitability and strong financial returns.


* **Operational Cost Burdens:** Labor, land preparation, and machinery overhead constitute the primary components of total farm expenditure, significantly outweighing variable chemical costs such as fertilizers and pesticides. Managing baseline operational costs is critical for preventing financial deficits.


* **Irrigation and Resource Efficiency:** Irrigation methodologies profoundly influence risk and financial return distributions. Advanced techniques like Drip and Sprinkler systems demonstrate superior water-use efficiency (`Water_Efficiency_t_per_1000m3`) compared to traditional flood irrigation, mitigating vulnerability to seasonal rainfall variations.


* **Seasonal Performance Patterns:** Seasonal groupings (`Kharif`, `Rabi`, and `Zaid`) highlight distinct variations in average yield and net profit, with Kharif cycles generally benefiting from favorable monsoon rainfall distributions and higher aggregate returns.



### Strategic & Evidence-Based Recommendations

* **Adoption of Precision Irrigation:** Farming operations and agricultural planners should accelerate transitions toward micro-irrigation systems (Drip and Sprinkler) to optimize water-use efficiency and safeguard profit margins against unpredictable water shortages.


* **Cost-Structure Optimization:** Producers operating in low-margin staple crop categories must implement cost-control measures and leverage localized cooperative pooling for machinery and labor to improve net return on investment (ROI).


* **Data-Driven Crop Planning:** Agricultural policy frameworks should support regional diversification toward high-ROI, water-efficient crops while deploying safety nets or subsidies for essential staple food production in vulnerable agro-climatic zones.



### Project Limitations

* **Proxy and Synthetic Estimation Dependencies:** Certain economic variables—such as itemized labor versus equipment depreciation costs—rely on simulated financial distributions rather than real-time transactional accounting.


* **Geographical Generalization Limits:** The scope is constrained to specific districts and states within the dataset, meaning findings require localized calibration before scaling to entirely different agro-ecological zones.


* **Exclusion of External Market Shocks:** Macroeconomic price volatility, sudden export/import policy shifts, and extreme localized pest epidemics are modeled via risk percentages rather than dynamic time-series shocks.



### Final Remarks

This major project demonstrates the critical value of data science applications in modern agriculture. By bridging environmental parameters, input expenditures, and financial outcomes, the analytical pipeline provides actionable intelligence for farmers, agricultural economists, and policymakers striving toward sustainable and profitable food security.
"""